# require 'tao_editor/components/toolbar_items/base'
# require 'tao_editor/components/toolbar_items/command_item_component'
# require 'tao_editor/components/toolbar_items/mark_item_component'
# require 'tao_editor/components/toolbar_items/list_item_component'
# require 'tao_editor/components/toolbar_items/block_item_component'
# require 'tao_editor/components/toolbar_items/menu_item_component'
# require 'tao_editor/components/toolbar_items/align_item_component'
# require 'tao_editor/components/toolbar_items/table_item_component'
