dist: trusty
sudo: false
language: ruby
cache:
  bundler: true
  yarn: true
addons:
  chrome: stable
rvm:
  - 2.4.1
node_js:
  - 'node'
before_install:
  - yarn
script:
  - bundle exec rake test
  - yarn run ci
